openapi: 3.0.0
info:
    title: Jobs API
    contact: {}
    version: '1.0'
servers:
    - url: https://jobs-api-0q3j.onrender.com/api/v1
      variables: {}
paths:
    /auth/register:
        post:
            tags:
                - Auth
            summary: register-user
            operationId: register-user
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/register-user-request'
                                - example:
                                      name: example
                                      email: example@gmail.com
                                      password: strongPass
                        example:
                            name: example
                            email: example@gmail.com
                            password: strongPass
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /auth/login:
        post:
            tags:
                - Auth
            summary: login-user
            operationId: login-user
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/login-user-request'
                                - example:
                                      email: example@gmail.com
                                      password: strongPass
                        example:
                            email: example@gmail.com
                            password: strongPass
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: create-job
            operationId: create-job
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/create-job-request'
                                - example:
                                      company: ourCompany
                                      position: Intern
                        example:
                            company: ourCompany
                            position: Intern
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: get-all-jobs
            operationId: get-all-jobs
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: string
              required: true
              description: the job id
        get:
            tags:
                - Jobs
            summary: get-single-job
            operationId: get-single-job
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        patch:
            tags:
                - Jobs
            summary: update-job
            operationId: update-job
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/update-job-request'
                                - example:
                                      company: newCompany
                                      position: Back-end Dev
                        example:
                            company: newCompany
                            position: Back-end Dev
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: delete-job
            operationId: delete-job
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        register-user-request:
            title: register-user-request
            required:
                - name
                - email
                - password
            type: object
            properties:
                name:
                    type: string
                email:
                    type: string
                password:
                    type: string
            example:
                name: example
                email: example@gmail.com
                password: strongPass
        login-user-request:
            title: login-user-request
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: example@gmail.com
                password: strongPass
        create-job-request:
            title: create-job-request
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: ourCompany
                position: Intern
        update-job-request:
            title: update-job-request
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: newCompany
                position: Back-end Dev
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Auth
      description: ''
    - name: Jobs
      description: ''
