openapi: 3.0.0
info:
    title: Jobs API
    contact: {}
    version: '1.0'
servers:
    - url: https://jobs-api-0q3j.onrender.com/api/v1
      variables: {}
paths:
    /auth/register:
        post:
            tags:
                - Auth
            summary: register-user
            operationId: register-user
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/register-user-request'
                                - example:
                                      name: uni
                        example:
                            name: uni
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /auth/login:
        post:
            tags:
                - Auth
            summary: login-user
            operationId: login-user
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/login-user-request'
                                - example:
                                      email: anshgupta@gmail.com
                                      password: newsecret
                        example:
                            email: anshgupta@gmail.com
                            password: newsecret
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: create-job
            operationId: create-job
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/create-job-request'
                                - example:
                                      company: amazon
                                      position: editor
                        example:
                            company: amazon
                            position: editor
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: get-all-jobs
            operationId: get-all-jobs
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: string
              required: true
              description: the job id
        get:
            tags:
                - Jobs
            summary: get-single-job
            operationId: get-single-job
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        patch:
            tags:
                - Jobs
            summary: update-job
            operationId: update-job
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/update-job-request'
                                - example:
                                      company: ms
                                      position: testing
                        example:
                            company: ms
                            position: testing
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: delete-job
            operationId: delete-job
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        register-user-request:
            title: register-user-request
            required:
                - name
            type: object
            properties:
                name:
                    type: string
            example:
                name: uni
        login-user-request:
            title: login-user-request
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: anshgupta@gmail.com
                password: newsecret
        create-job-request:
            title: create-job-request
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: amazon
                position: editor
        update-job-request:
            title: update-job-request
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: ms
                position: testing
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Auth
      description: ''
    - name: Jobs
      description: ''
